### ISSUE TITLE
Null point exception being thrown in tasker when "KeepInput" flag isn't set

### ISSUE THREAD

**Issue by epag** [epag/wresTicketTesting#131]
---

Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Redmine Issue: 124860, https://vlab.noaa.gov/redmine/issues\124860
Original Date: 2024-01-05

---

Was doing some testing and I noticed this NPE keep popping up. It wasn't affecting anything results wise, but not a good idea to have NPEs in the code 

```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.redisson.liveobject.core.AccessorInterceptor.intercept(java.lang.reflect.Method, java.util.concurrent.Callable, Object[], Object, org.redisson.api.RMap)" is null
2024-01-05 13:30:01     at wres.tasker.JobMetadata$ByteBuddy$ycq20xO7.getKeepInput(Unknown Source)
2024-01-05 13:30:01     at wres.tasker.JobResults.deleteInputs(JobResults.java:1383)
2024-01-05 13:30:01     at wres.tasker.JobResults.deleteInputs(JobResults.java:1368)
2024-01-05 13:30:01     at wres.tasker.JobResults$JobResultWatcher.call(JobResults.java:483)
2024-01-05 13:30:01     at wres.tasker.JobResults$JobResultWatcher.call(JobResults.java:313)
2024-01-05 13:30:01     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-01-05 13:30:01     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-01-05 13:30:01     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-01-05 13:30:01     at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T18:36:07Z

---

Should be as simple as setting the default to false or to do a null check

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T18:37:24Z

---

Also it was popping up in the tasker logs just for full information

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **hank.herr** (hank.herr)
Original Date: 2024-01-05T18:40:16Z

---

Thanks for finding this, Evan.

Either approach should be fine, but include a null check regardless of whether there should be a default can't hurt. Might just make both changes.

Thanks again,

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T19:38:25Z

---

hm, odd. Looks like the default was already set to false for this, and adding in a null check at the point where we get a NPE doesn't solve anything. This might be more involved then I originally though. A bit stumped on this. Ill revisit this on monday

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T19:43:15Z

---

Yeah, it looks like this line @Objects.nonNull( sharedData.getKeepInput() )@ is still the line where the NPE is happening after I added it, which seems impossible to me

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **hank.herr** (hank.herr)
Original Date: 2024-01-05T19:47:40Z

---

Evan,

Is this happening while obtaining job results for a job that was created before the code change to add @keepInput@?  I'm not sure I really tested that thoroughly. I just assumed that seeing @boolean keepInput = false@ would default it to false if @keepInput@ was not defined in the persister.  

I also wonder if it would be resolved if that was changed to @Boolean@.  

Anyway, let me know what you find. Have a great weekend!

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **hank.herr** (hank.herr)
Original Date: 2024-01-05T19:48:49Z

---

evan.pagryzinski wrote:
> Yeah, it looks like this line @Objects.nonNull( sharedData.getKeepInput() )@ is still the line where the NPE is happening after I added it, which seems impossible to me

The stack trace implies its happening within the @getKeepInput@, itself, not after its obtained as null. That's why I wonder if its related to my use of @boolean@ vs @Boolean@ or if its an older evaluation in the persister.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T19:51:15Z

---

hank.herr wrote:@@
> evan.pagryzinski wrote:
> > Yeah, it looks like this line @Objects.nonNull( sharedData.getKeepInput() )@ is still the line where the NPE is happening after I added it, which seems impossible to me
> 
> The stack trace implies its happening within the @getKeepInput@, itself, not after its obtained as null. That's why I wonder if its related to my use of @boolean@ vs @Boolean@ or if its an older evaluation in the persister.
> 
> Hank

I also tried swapping from @boolean@ to @Boolean@ and its still there

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-01-05T20:04:12Z

---

It isn't the @Boolean@ that's null, it's the thing that contains it and from which you are requesting the @Boolean@, in other words one level up from where you think.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T20:36:47Z

---

james.d.brown wrote:
> It isn't the @Boolean@ that's null, it's the thing that contains it and from which you are requesting the @Boolean@, in other words one level up from where you think.

Its strange because this is also not being hit when I test this and we still get the NPE at the same line:
```
        if ( Objects.isNull( sharedData ) ) {
            LOGGER.error( "We have no JobMetadata" );
            return;
        }

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **hank.herr** (hank.herr)
Original Date: 2024-01-05T20:47:14Z

---

Took a look in staging... It appears that the problem occurs when evaluations do +not+ include posted data. 

The @keepInput@ attribute is expressly set only if the evaluation includes posted input:

```<code class="java">
...
        // If the caller wishes to post input data: parameter postInput=true
        if ( postInput )
        {
            // Pause before sending. Parse the declaration and add inputs before
            // sending along. This request will result in 201 created response
            // and the caller must send another request saying "I have finished
            // posting input."
            JOB_RESULTS.setJobMessage( jobId, jobMessage.toByteArray() );
            JOB_RESULTS.setAwaitingPostInputData( jobId );
            JOB_RESULTS.setKeepPostedInputData( jobId, keepInput );
...
</code>
```

Otherwise, its relying on the declaration of @keepInput@ inside of the @JobMetadata@ to populate it with a default value:

```<code class="java">
    private boolean keepInput = false;
</code>
```

I'm not sure I understand why the error happens, but perhaps we should just make sure to set the @keepInput@ value every time, whether data is posted or not?  However, we still wouldn't understand why its a problem; we would just be working around it.  

There are debug statements that dump the @JobMetadata@ prior to deleting the inputs that could be informative if they are turned on:

```<code class="java">
            // Checking for HTTP OK status
            if ( resultValue == HttpStatus.ok().status() )
            {
                sharedData.setJobState( JobMetadata.JobState.COMPLETED_REPORTED_SUCCESS );
                LOGGER.debug( "Shared metadata after setting job state: {}",
                              jobMetadata );
                JobResults.deleteInputs( jobMetadata );
            }
            // We use 409 to signify a canceled evaluation
            else if ( resultValue == HttpStatus.error409().status() )
            {
                sharedData.setJobState( JobMetadata.JobState.CANCELED );
                LOGGER.debug( "Shared metadata after setting job state: {}",
                              jobMetadata );
                JobResults.deleteInputs( jobMetadata );
            }
</code>
```

Anyway, there is some investigation that can be done on Monday. I can do that investigation, since I created the problem, if you don't have the time to do so, Evan.

Again, Have a great weekend! This time I won't be returning. :)

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-05T20:52:33Z

---

I should have time to poke around on monday, things are moving pretty smoothly with the persistent cache stuff and I doubt it will take me to friday of next week to wrap that up

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-01-05T21:12:23Z

---

evan.pagryzinski wrote:
> Its strange because this is also not being hit when I test this and we still get the NPE at the same line:
> [...]

The clue, such as it is, is all in this part:

> Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.redisson.liveobject.core.AccessorInterceptor.intercept(java.lang.reflect.Method, java.util.concurrent.Callable, Object[], Object, org.redisson.api.RMap)" is null

This implies a level of indirection (@AccessorInterceptor@) in the attempt to access state and it's the indirect thing that is generating a null reference. It's hard for me to speculate further about what the indirection represents without reviewing the code, but this pattern of NPE can be confusing/frustrating because the subject of the invocation is not the thing that is null here, it's the thing above it.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-08T15:32:20Z

---

Alright, so setting @keepInput@ for both flows and not just the post flow removes the NPE. 

However, I am still not sure why this is happening. I have it so we are setting @keepInput@ in the @JobMetadata@ instantiation. So unsure why it is throwing an NPE for this but not for @jobMessage@ for example. 

```
    public JobMetadata( String id )
    {
        this.setId( id );
        ...
        this.jobMessage = null;
        this.keepInput = false;
        ...
        this.databasePort = null;
    }

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-08T15:33:35Z

---

Guess we can just set @keepInput@ for both flows and be done with this, but don't love the idea that setting a field in the instantiation of an object we are storing in the persistor is not being set

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-01-08T16:01:58Z

---

Alright, I went ahead and just did the fix for now. Can't think of why this is occuring, but unsure what to look into. NPE is gone
