### ISSUE TITLE
Implement build and basic testing for github

### ISSUE THREAD

**Issue by epag** [epag/wresTicketTesting#146]
---

Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Redmine Issue: 128565, https://vlab.noaa.gov/redmine/issues\128565
Original Date: 2024-04-05
Original Assignee: evan.pagryzinski

---

Copy over function of our current Jenkins jobs responsible for building and executing unit tests and select tests using h2

build/unit tests: https://vlab.noaa.gov/jenkins/job/Verify_OWP_WRES/4928/
h2 tests: https://vlab.noaa.gov/jenkins/job/OWP_WRES_Tests/595/

WIki:
https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration
https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-jenkins-to-github-actions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-05T14:37:12Z

---

I currently put 64 hours for this, but if any ticket is likely to have creep it will be this one as this will be when I am actively playing with the structure of the github actions flows. May bump this to 128 estimate if things are less intuitive than I expect with my current investigation

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-05T14:40:06Z

---

Also we are going to have much more granular control of when we allow code to be submited.

My thoughts are:

- Failing build or unit tests rejects code from being merged (You need to wait for this to complete after pushing your code to a PR and before merging into master)
- h2 tests (I remember these having been flaky at times, correct me if I am wrong) will run after code is merged

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-05T14:46:40Z

---

Actually, just to give myself some grace, and I am going to go ahead and bump the timeline now. Always better to come in under than above

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T13:41:58Z

---

Still a way to go until we reach parity with the jenkins job, but found a template for gradle with java github action templates and was able to get a @./gradlew build@ to run on a push of new code.

!Screenshot%202024-04-26%20093951.png!

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T13:49:31Z

---

One question I have immediately is that I see we are using OpenJDK11-Corretto in Jenkins. Is this what our hosts are using or am I good to test/build against jdk17? 

Shouldn't be an issue to go back, just wasn't sure if this was a limitation of our old implementation

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-04-26T13:51:43Z

---

To run gradle, I think. Not to actually build the code, because that is handled with a gradle toolchain. As you will see, the @build.gradle@ _requires_ jdk17 or higher because we are using jdk17 features.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-04-26T13:53:03Z

---

```<code class="groovy">
// The target Java version for use in a gradle toolchain
def final TARGET_JDK = 17

java
{
    withJavadocJar()
    withSourcesJar()
    
     // Declare the Java version, self-contained to the build
    toolchain 
    {
        languageVersion = JavaLanguageVersion.of( TARGET_JDK )
    }
}
</code>
```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-04-26T13:54:10Z

---

To be clear, a gradle toolchain is a self-contained build pipeline that acquires the necessary jdk and installs it locally if a suitable one (jdk17, in this case) is not available.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T14:01:55Z

---

james.d.brown wrote:
> To be clear, a gradle toolchain is a self-contained build pipeline that acquires the necessary jdk and installs it locally if a suitable one (jdk17, in this case) is not available.

So just to make sure I am understanding correctly, the JDK that I am setting for this github action should be irrelevant because our java version we are declaring within the gradle toolchain will be what actually determines what is used for building/testing

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-04-26T14:11:24Z

---

Yes or, rather, it is related to the version of gradle you are using and what it requires, not the version targeted by our build, which is always jdk17. To keep things simple, I would use jdk17 to run gradle (and, separately, the @build.gradle@ will instruct gradle to use jdk17 to build the wres).

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T14:23:07Z

---

I need to do closer investigation on how things are being done in the jenkins command specifically because I know we don't just do @./gradlew build@. Im not sure what parts of it a quirks for Jenkins specifically and what all we need to have in github actions. Like I see some stuff related to "having exactly 1 zip per distribution in the workspace", but I think github breaks things apart on the action run/release version so I think this is obsolete. However, progress is moving FAST thankfully and fingers crossed.


Have it so we are caching the artifacts created by @./gradlew build@ and that build is also successfully running all of the unit tests.

Archiving artifacts
```
Finalizing artifact upload
Artifact build-artifacts.zip successfully finalized. Artifact ID 1451094921
Artifact build-artifacts has been successfully uploaded! Final size is 316027604 bytes. Artifact ID is 1451094921
Artifact download URL: https://github.com/NOAA-OWP/wres/actions/runs/8849546643/artifacts/1451094921

```

Snip from build/tests
```
2024-04-26T14:11:25.6624420Z [0K[1;32mSUCCESS: [39mExecuted 27 tests in 2.5s (2 skipped)[m
2024-04-26T14:11:25.6625102Z 
2024-04-26T14:11:25.6625111Z 
2024-04-26T14:11:25.6625419Z > Task :wres-writing:check
2024-04-26T14:11:25.6626057Z > Task :wres-writing:build
2024-04-26T14:11:25.7124292Z 
2024-04-26T14:11:25.7124623Z BUILD SUCCESSFUL in 4m 49s

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T14:26:02Z

---

Wiki on programmatically getting the action artifacts via an API (Will likely need to use this for external testing)

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T14:49:29Z

---

Weird that we weren't seeing this before, but we should fix these issues flagged by github:

!Screenshot%202024-04-26%20104819.png!

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T14:59:09Z

---

Not to jinx myself, but I may be able to close this ticket out way ahead of schedule. We have parity to the jenkins @VERIFY_OWP_WRES@ job right now that automatically runs on push and pull requests on master.

The artifacts are stored (For 60 days only) that are created from this build. I need to look into how we can have these persisted permanently for a release. The release pipeline will be separate though and I believe has persistent storage 

!Screenshot%202024-04-26%20105331.png!

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-26T15:46:47Z

---

Setting I will want hank to turn on:

- Auto abort a commit if it causes the build/unit tests, or the system tests to fail

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-29T13:03:16Z

---

Apologies for all the failure emails you are bound to see today

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-29T16:13:10Z

---

Just to keep you all updated, having a hard time assigning the versions of various zips to variables to run the 500 series tests. I _could_ embed the commands into the test suit command, but that would make things horribly unreadable so I am avoiding that at all costs

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-29T17:04:45Z

---

It was that you cannot declare variables in the same grouping of steps that you use them

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-29T20:07:35Z

---

Im still investigating but seems like there is some issue either spinning up or testing against the h2 database:

```
Caused by:
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]         java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Could not get a raw database connection. [in thread "Test worker"]
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at wres.io.database.Database.getRawConnection(Database.java:143)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at wres.io.database.DatabaseOperations.migrateDatabase(DatabaseOperations.java:206)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at wres.systests.ScenarioHelper.<clinit>(ScenarioHelper.java:77)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at wres.systests.Scenario052.beforeIndividualTest(Scenario052.java:59)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-04-29T19:59:50.246+0000 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2024-04-29T19:59:50.247+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-04-29T19:59:50.248+0000 [DEBUG] [TestEventLogger]             ... 16 more

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T14:08:58Z

---

Seems like we cannot instantiate the database, this could be due to some escaping issue. I am going to attempt to go back to a carbon copy of what we having in jenkins and seeing if that fixes things:

```
2024-04-30T13:44:44.396+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.395+0000 WARN SettingsFactory Unable to extract database host, port, or name from jdbc url jdbc:h2:mem:test;MODE=REGULAR;TRACE_LEVEL_FILE=4;DB_CLOSE_DELAY=-1;INIT=create schema if not exists wres;
2024-04-30T13:44:44.415+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.415+0000 INFO ConnectionSupplier Creating a database connection pool with 13 connections...
2024-04-30T13:44:44.429+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.428+0000 INFO HikariDataSource HikariPool-1 - Starting...
2024-04-30T13:44:44.596+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.596+0000 INFO HikariPool HikariPool-1 - Added connection conn0: url=jdbc:h2:mem:test user=WRES_USER
2024-04-30T13:44:44.598+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.598+0000 INFO HikariDataSource HikariPool-1 - Start completed.
2024-04-30T13:44:44.599+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.599+0000 INFO ConnectionSupplier Creating a high-priority database connection pool with 5 connections...
2024-04-30T13:44:44.599+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.599+0000 INFO HikariDataSource HikariPool-2 - Starting...
2024-04-30T13:44:44.601+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.601+0000 INFO HikariPool HikariPool-2 - Added connection conn1: url=jdbc:h2:mem:test user=WRES_USER
2024-04-30T13:44:44.601+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.601+0000 INFO HikariDataSource HikariPool-2 - Start completed.
2024-04-30T13:44:44.614+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.614+0000 INFO DatabaseOperations Beginning database migration. This takes time.
2024-04-30T13:44:44.615+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.615+0000 WARN DatabaseLockManagerNoop Using no-op database lock manager, appropriate for in-memory evaluations only.
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     2024-04-30T13:44:44.624+0000 ERROR Scenario052 testScenario(wres.systests.Scenario052)
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     java.lang.ExceptionInInitializerError: null
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     	at wres.systests.Scenario052.beforeIndividualTest(Scenario052.java:59)
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-04-30T13:44:44.627+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
2024-04-30T13:44:44.628+0000 [DEBUG] [TestEventLogger]     	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2024-04-30T13:44:44.629+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-04-30T13:44:44.629+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2024-04-30T13:44:44.629+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2024-04-30T13:44:44.629+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2024-04-30T13:44:44.630+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-30T13:44:44.631+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at jdk.proxy2/jdk.proxy2.$Proxy30.processTestClass(Unknown Source)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
2024-04-30T13:44:44.632+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     Caused by: java.lang.IllegalStateException: Could not get a raw database connection.
2024-04-30T13:44:44.633+0000 [DEBUG] [TestEventLogger]     	at wres.io.database.Database.getRawConnection(Database.java:143)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at wres.io.database.DatabaseOperations.migrateDatabase(DatabaseOperations.java:206)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at wres.systests.ScenarioHelper.<clinit>(ScenarioHelper.java:77)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	... 46 common frames omitted
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:test;MODE=REGULAR;TRACE_LEVEL_FILE=4;DB_CLOSE_DELAY=-1;INIT=create schema if not exists wres;
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at wres.io.database.Database.getRawConnection(Database.java:372)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	at wres.io.database.Database.getRawConnection(Database.java:139)
2024-04-30T13:44:44.634+0000 [DEBUG] [TestEventLogger]     	... 48 common frames omitted

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T14:29:01Z

---

Got things to be "working" exactly like the jenkins job, but still getting an error. I think the root is this:

```
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:test;MODE=REGULAR;TRACE_LEVEL_FILE=4;DB_CLOSE_DELAY=-1;INIT=create schema if not exists wres;

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T14:52:48Z

---

evan.pagryzinski wrote:
> Got things to be "working" exactly like the jenkins job, but still getting an error. I think the root is this:
> 
> [...]

I found a chain of comments that are referencing this from when we were adding externalized graphics to the h2 tests, going to dig there https://vlab.noaa.gov/redmine/issues/103431#note-27

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T14:54:47Z

---

Hahaha, James comments are not raising my hopes

!Screenshot%202024-04-30%20105402.png!

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T15:21:17Z

---

Hmmmm, interesting. I followed the ticket and came to this code that fixed things:

```
    // Initialize all available driver classes for known databases. Strictly, this should not be necessary for JDBC 4.0+
    // drivers, which should be loaded automatically. However, #103770 suggests otherwise in some environments or class 
    // loading contexts.
    static
    {
        for ( DatabaseType nextType : DatabaseType.values() )
        {
            try
            {
                Class.forName( nextType.getDriverClassName() );
            }
            catch ( ClassNotFoundException classError )
            {
                LOGGER.debug( "Failed to load the database driver class {}.", nextType.getDriverClassName() );
            }
        }
    }

```

I removed this chunk of code when I moved @DatabaseSettings@ to a POJO. It didn't cause issues on the jenkins server, but we are now seeing the issue on github. Interesting. I wonder if add this back in some way will fix things

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T15:37:49Z

---

Huh, well adding that code back to the @DatabaseSettings@ seemed to fix things in github. Wonder why jenkins was unaffected by that. Anyways, im going to make a quick change to our main codebase to add that change in for the future deploy

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **james.d.brown** (james.d.brown)
Original Date: 2024-04-30T15:39:29Z

---

The vagaries of class loading. I would take the win and not ask too many questions :)

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-04-30T20:19:33Z

---

Got all of the system tests done that we were testing on jenkins! 

Need to clean up some stuff and verify all the stuff being archived, but this ticket should be wrapped up way ahead of schedule

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-05-01T15:33:39Z

---

I am going to turn off debug mode for our systests in github. I see this line a bunch and ideally we want to avoid any leaks:

```
2024-05-01T15:27:32.639+0000 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 
#############################################################################
   WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

   Debug level logging will leak security sensitive information!

   https://docs.gradle.org/7.6/userguide/logging.html#sec:debug_security
#############################################################################

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-05-01T15:36:27Z

---

That being said, I think this ticket is pretty much done. Going to take one more pass through of things, but this is how it looks now:

!Screenshot%202024-05-01%20113152.png!

For pushes to and PRs against master we will kick off a build. A successful build will then trigger a system test to execute

(For future reference, or now, we should make it so if one of these two jobs fail that we auto-revert the commit/dont allow a PR to be submitted without these running successfully)

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-05-01T15:42:42Z

---

I encourage anyone that wants to, to take a look through the changes and let me know if you have any questions/recommendations

current actions:
https://github.com/NOAA-OWP/wres/actions

current workflows:
https://github.com/NOAA-OWP/wres/tree/master/.github/workflows

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **evan.pagryzinski** (evan.pagryzinski)
Original Date: 2024-05-01T18:01:13Z

---

Think we are good here, will start the next ticket
